set(InstallLocation /opt/Elite)

SET(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})

SET(CPACK_GENERATOR "STGZ;TGZ;DEB")
SET(CPACK_INCLUDE_TOPLEVEL_DIRECTORY ON)
SET(CPACK_PACKAGE_NAME "elite-lang")
SET(CPACK_PACKAGE_VERSION "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")
SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
SET(CPACK_PACKAGE_CONTACT "sunxfancy@gmail.com")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Elite compiler")
SET(CPACK_PACKAGING_INSTALL_PREFIX "/")
SET( CPACK_PACKAGE_DEFAULT_LOCATION ${InstallLocation})

install(TARGETS elite RUNTIME DESTINATION bin)

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/conf
        DESTINATION ${InstallLocation}
        FILE_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
        GROUP_EXECUTE GROUP_READ WORLD_READ
        DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
        GROUP_EXECUTE GROUP_READ WORLD_READ)
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/packages
        DESTINATION ${InstallLocation}
        FILE_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
        GROUP_EXECUTE GROUP_READ WORLD_READ
        DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
        GROUP_EXECUTE GROUP_READ WORLD_READ
        PATTERN ".git" EXCLUDE)
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/tools
        DESTINATION ${InstallLocation}
        FILE_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
        GROUP_EXECUTE GROUP_READ WORLD_READ
        DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
        GROUP_EXECUTE GROUP_READ WORLD_READ
        PATTERN ".git" EXCLUDE)

INCLUDE(CPack)
